### ISSUE TITLE
HL7 service has error when run at command line

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.health#108]
This also applies to OBX service.  The issue is that the packaging was different between command line and development.  When adding required jars to topology, we point to the wrong location.

To get around the problem, copy release/opt/lib/* to release/release/opt/lib* after the release is built.

This should be fixed soon.

[streamsadmin@streamsqse release]$ ./runAdt.sh
Exception in thread "main" java.lang.IllegalArgumentException: File not found. Invalid third party dependency location:/home/streamsadmin/health/git/streamsx.health/ingest/hl7/com.ibm.streamsx.health.hapi/release/release/opt/lib/hapi-base-2.2.jar
	at com.ibm.streamsx.topology.internal.core.DependencyResolver.addJarDependency(DependencyResolver.java:93)
	at com.ibm.streamsx.topology.internal.core.JavaFunctional.addJarDependency(JavaFunctional.java:133)
	at com.ibm.streamsx.topology.Topology.addJarDependency(Topology.java:552)
	at com.ibm.streamsx.health.hapi.services.AbstractHL7Service.addDependencies(AbstractHL7Service.java:31)
	at com.ibm.streamsx.health.hapi.services.AdtIngest.run(AdtIngest.java:38)
	at com.ibm.streamsx.health.hapi.services.AdtIngest.main(AdtIngest.java:30)

**Comment by chanskw** [comment]
Fixed in develop
