### ISSUE TITLE
PatientsMonitoringDemo cannot build

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.health#78]
missing .toolkits directory and its zip file.

**Comment by cancilla** [comment]
The files are there: https://github.com/IBMStreams/streamsx.health/tree/develop/samples/PatientsMonitoringDemo/.toolkits

It may have been an issue with the .gitignore in the root project. It was ignoring .zip and .toolkits for some reason. Try pulling into your local workspace again.

**Comment by chanskw** [comment]
I put the projects into a branch.  I think we want to build the projects from the rules project that I have delivered.

The branch is here:  https://github.com/IBMStreams/streamsx.health/tree/feature/79-AddRulesProj

**Comment by chanskw** [comment]
Now that the file is fixed, the gradle execute fails:

Mar 17, 2017 8:33:36 PM com.ibm.streamsx.topology.internal.process.ProcessOutputToLogger run
SEVERE: CDISP0121W WARNING: The following toolkit file is missing: /home/streamsadmin/temp/git/streamsx.health/ingest/common/com.ibm.streamsx.health.ingest/toolkit.xml.
Mar 17, 2017 8:33:38 PM com.ibm.streamsx.topology.internal.process.ProcessOutputToLogger run
SEVERE: CDISP0385E ERROR: The VisualizationDemo toolkit requires version [1.0.0,2.0.0) of the com.ibm.streamsx.health.ingest toolkit, but version [1.0.0,2.0.0) of the com.ibm.streamsx.health.ingest toolkit is not available.
Mar 17, 2017 8:33:38 PM com.ibm.streamsx.topology.internal.process.ProcessOutputToLogger run
SEVERE: CDISP0385E ERROR: The com.ibm.streamsx.health.analyze.vital toolkit requires version [1.0.0,2.0.0) of the com.ibm.streamsx.health.ingest toolkit, but version [1.0.0,2.0.0) of the com.ibm.streamsx.health.ingest toolkit is not available.
Mar 17, 2017 8:33:38 PM com.ibm.streamsx.topology.internal.process.ProcessOutputToLogger run
SEVERE: CDISP0131E ERROR: Errors occurred while the toolkits were loading.
Mar 17, 2017 8:33:38 PM com.ibm.streamsx.topology.internal.streams.InvokeSc invoke
INFO: SPL compiler complete: return code=1
Exception in thread "main" java.lang.Exception: SPL compilation failed!
        at com.ibm.streamsx.topology.internal.streams.InvokeSc.invoke(InvokeSc.java:133)
        at com.ibm.streamsx.topology.internal.context.BundleStreamsContext.doSPLCompile(BundleStreamsContext.java:108)
        at com.ibm.streamsx.topology.internal.context.BundleStreamsContext.submit(BundleStreamsContext.java:74)
        at com.ibm.streamsx.topology.internal.context.DistributedStreamsContext.submit(DistributedStreamsContext.java:35)
        at com.ibm.streamsx.topology.internal.context.StreamsContextImpl.submit(StreamsContextImpl.java:19)
        at com.ibm.streamsx.health.demo.service.UIWrapperService.run(UIWrapperService.java:33)
        at com.ibm.streamsx.health.demo.PatientsMonitoringDemo.main(PatientsMonitoringDemo.java:74)
:samples:PatientsMonitoringDemo:execute FAILED


Need to manually build the health.ingest project.

**Comment by chanskw** [comment]
I am fixing this along with #79.  Replacing the zip file with the new rules projects that get delivered.

**Comment by chanskw** [comment]
Fixed.
